# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('address', models.TextField(max_length=12, verbose_name='Dirección')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
