# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('l', 'Lunes'), ('m', 'Martes'), ('i', 'Miercoles'), ('j', 'Jueves'), ('v', 'Viernes'), ('s', 'Sabado'), ('d', 'Domingo')], default='l', max_length=2, verbose_name='Dia de la semana')),
                ('service_time', models.TimeField(choices=[('8:00', '8:00-9:00'), ('9:00', '9:00-10:00'), ('10:00', '10:00-11:00')], default='8:00', verbose_name='Hora de Servicio')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='Lugar')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='places',
            field=models.ManyToManyField(through='provider.ProviderPlace', to='place.Place'),
        ),
    ]
