# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20161119_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='places',
            field=models.ManyToManyField(related_name='lugares', through='provider.ProviderPlace', to='place.Place', verbose_name='Lugares'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='specialty',
            field=models.ManyToManyField(related_name='especialidades', to='provider.Specialty', verbose_name='Especialidades'),
        ),
    ]
