# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20161119_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
