# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20161120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='places',
            field=models.ManyToManyField(through='provider.ProviderPlace', to='place.Place', verbose_name='Lugares'),
        ),
        migrations.AlterField(
            model_name='providerplace',
            name='service_time',
            field=models.TimeField(default='08:00:00', verbose_name='Hora de Servicio'),
        ),
    ]
