# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20161120_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerplace',
            name='service_time',
            field=models.CharField(choices=[('01:00:00', '1:00-2:00'), ('02:00:00', '2:00-3:00'), ('03:00:00', '3:00-4:00'), ('04:00:00', '4:00-5:00'), ('05:00:00', '5:00-6:00'), ('06:00:00', '6:00-7:00'), ('07:00:00', '7:00-8:00'), ('08:00:00', '8:00-9:00'), ('09:00:00', '9:00-10:00'), ('10:00:00', '10:00-11:00'), ('11:00:00', '11:00-12:00'), ('12:00:00', '12:00-13:00'), ('13:00:00', '13:00-14:00'), ('14:00:00', '14:00-15:00'), ('15:00:00', '15:00-16:00'), ('16:00:00', '16:00-17:00'), ('17:00:00', '17:00-18:00')], default='08:00:00', max_length=8, verbose_name='Hora de Servicio'),
        ),
    ]
