# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_auto_20161120_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='places',
            field=models.ManyToManyField(related_name='horarios', through='provider.ProviderPlace', to='place.Place', verbose_name='Lugares'),
        ),
    ]
