# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=None, verbose_name='Edad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
    ]
