# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20161119_1211'),
        ('client', '0002_auto_20161119_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='Cliente')),
                ('providerplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.ProviderPlace', unique=True, verbose_name='Relacion Proveedor-Lugar')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='agenda',
            field=models.ManyToManyField(related_name='servicio_agendado', through='client.ClientProvider', to='provider.ProviderPlace', verbose_name='Relacion Cliente-ProveedorLugar'),
        ),
    ]
