# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20161119_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
    ]
